### ISSUE TITLE
Why not make a synchroniser based on isolate messaging

### ISSUE THREAD

**Issue by sandrobilbeisi** [angel-dart/multiserver#2]
Why not make a synchroniser based on isolate messaging ?

an isolate subordinate to the master is the hub that synchronises its child isolates through use of
SendPort / ReceivePort

I'm using a similar arrangement for high-traffic situations 
It's much more efficient that the other choices such as Redis / mongodb / memcached because these can reach very high latency under load

**Comment by thosakwe** [comment]
Yeah, that's a great idea. I'll roll one out with the next commit. I can imagine that database-based session management could be a bottleneck.

**Comment by thosakwe** [comment]
https://github.com/angel-dart/sync takes care of this effectively. Hooray!
